name: Cog Remote Push

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cog v0.14.2
        run: |
          mkdir -p /tmp/cog-bin
          curl -L https://github.com/replicate/cog/releases/download/v0.14.2/cog_Linux_x86_64 -o /tmp/cog-bin/cog
          chmod +x /tmp/cog-bin/cog
          echo "/tmp/cog-bin" >> $GITHUB_PATH
          /tmp/cog-bin/cog --version

      - name: Log in to Replicate
        run: |
          echo "$REPLICATE_CLI_TOKEN" | cog login --token-stdin
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build and push to Replicate
        run: |
          cog push r8.im/${{ secrets.REPLICATE_USERNAME }}/cyberpony-multi-lora
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
