name: Cog Remote Push

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Force install of latest Cog (overrides cached 0.14.x)
      - name: Install latest Cog binary
        run: |
          mkdir -p /tmp/cog-bin
          curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64 -o /tmp/cog-bin/cog
          chmod +x /tmp/cog-bin/cog
          echo "/tmp/cog-bin" >> $GITHUB_PATH
          /tmp/cog-bin/cog --version

      # 🚀 Build & push with modern Cog
      - name: Build and push to Replicate
        run: |
          cog push r8.im/${{ secrets.REPLICATE_USERNAME }}/cyberpony-multi-lora
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
